# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'
require 'bundler'
Bundler.require

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'AutoLayout'

  #include styles
  app.files += Dir.glob(File.join(app.project_dir, 'lib/**/*.rb'))
end
