$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'
require 'bundler'
Bundler.require


Motion::Project::App.setup do |app|
  app.name = 'Hai'
  app.identifier = 'com.rubymotion.Hai'

  app.device_family = :iphone
end
